spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3307/cats_list}
spring.datasource.username=${DATABASE_USERNAME:user}
spring.datasource.password=${DATABASE_PASSWORD:password}
server.port=${PORT:8080}
